### ISSUE TITLE
Review of Internal Assessment Plan

### ISSUE THREAD

**Issue by MarcBehrens** [openETCS/internal-assessment#55]
The updateof the internal assessment plan is now released and ready for the review.

Please review the current deliverable D4.5.1 | openETCS Internal Assessment Plan

The review is open until 24.09.2015.

Document under review: 

 Type   | Name                                                     | due      | pdf | source
----|----|----|---|---
D4.5.1 | openETCS Internal Assessment Plan | revision Sep-2015 | [pdf](https://github.com/openETCS/internal-assessment/blob/master/Internal_Assessment_Plan/Internal_Assessment_Plan.pdf) | [source](https://github.com/openETCS/internal-assessment/blob/master/Internal_Assessment_Plan/Internal_Assessment_Plan.tex)

Role | Partner 
---|---
Product Owner | @FrederiqueVallee  
Review Team | @KlausRuedigerHase  @janWelte @marcbehrens @MariellePetitDoche @jensgerlach @JanWelvaarts @UweSteinkeFromSiemens  @AbdelnasirMohamed 
Key Customers WP1 | @KlausRuedigerHase  
Key Customers WP3 | @BerndHekele  @BaseliyosJacob 
Key Customers WP4 VnV-plan | @HardiHungar 
Key Customers WP5 | @openETCS/demonstrator-commiter 
Key Customers WP7 | @jastram

The role of the key customers is to guarantee completeness, accuracy and validity of the contents of a document.

Please contribute to the review according to the [QA- Review Process](https://github.com/openETCS/governance/blob/master/Review%20Process/OpenETCS_ReviewProcess_0.2.1.pdf?raw=true).

@openETCS/internal-assessment-committer 
@openETCS/validation-committers 
@openETCS/modeling

Please mention #55 within your issue or contribute with a pull request to the document itself.

**Comment by MarcBehrens** [comment]
relates to https://github.com/openETCS/product-backlog/issues/80

**Comment by HardiHungar** [comment]
I confirm participation in the review.

**Comment by janWelte** [comment]
I've send my final review comment via mail. Shall I also upload them to the repositiory somewhere?

**Comment by MarcBehrens** [comment]
due to a request the review is extedneded until Monday, 28.9.2015

**Comment by KlausRuedigerHase** [comment]
General remark: For my understanding the  suggested approach does not really reflect those issues that are driven by the agile/incremental development setting.  Please find here my comments in detail; only pages with remarks have been included in order to keep the file as compact as possible.
[D4-5-1_openETCS_Internal_Assessment_Plan_Review_KRH2.pdf](https://github.com/openETCS/internal-assessment/files/4256/D4-5-1_openETCS_Internal_Assessment_Plan_Review_KRH2.pdf)

**Comment by MarcBehrens** [comment]
Review comment from @HardiHungar:

The VnV plan will be available for internal assessment by end of October 2015.

Scope of the model: Even if the model includes track-side components, it would make sense to limit the scope of the Internal Assessment (IA) to the SW of the OBU. 
The OBU is a separate development target (as nobody wants to have all of ETCS provided by one manufacturer, for one reason). And therefore at least a part of openETCS should be to address a full development of the OBU, including a SW development. The process as defined in D2.3a is tailored towards that. (There is no useable process definition for the other ETCS components, nothing the IA could look at). 

Agile development: CENELEC permits an agile development. But once completed, the documentation should at least contain everything of a consistent linear development. I.e.: A sequence of verified refinement and implementation steps. If there is “historical” information on how the finally valid content of the artifacts came into existence (e.g. previous versions, final content through change history), this is permitted but makes everything more difficult to assess. 

And there is no way out of CENELEC conformance – if there is no practical way to use the results of openETCS in a real system (certified), no manufacturer will consider to do this. IMHO, the main idea of the IA is to identify the difference between what has been achieved and what would be needed for a CENELEC-compliant, full development. Having this difference identified, anybody has a sound basis to see what it would take to use the openETCS results. And we have an indication what we can do in the last month to improve upon the situation.

**Comment by MarcBehrens** [comment]
The review is closed, thank you very much for the contributions.

During the following revision phase the Internal Assessment Plan will be revised taking the input into account.

**Comment by MarcBehrens** [comment]
Review closing session:
participants: @FrederiqueVallee @norbertschaefer @AbdelnasirMohamed  @janWelte @UweSteinkeFromSiemens @marcbehrens

Answering the comments from @KlausRuedigerHase :

p1: 
- replace "shall be independant form the project" to read "The assessor is working according to the indendance criteria defined inside the standard EN17020" + adding standard reference
- define "Assessor" in this content to be the "independant safety assessor" according to EN17020
- the reporting is the deliverable mentioned in the chapter 4.3
- comment to "the model includes ..": from the scope written down in the FPP the EVC is the system under development and the environment simulation used for development and to qualify the EVC can be described ad RBC + Balises.

p7:
- echange WP3 with "...EVC development..."

p8:
- replace ".. the whole documentation ..." with "... the whole documentation and methods of the software development process...". adding "A table concerning the development methods according to CENELEC Appendix (tbd @AbdelnasirMohamed ) shall be described inside the plan."

p10:
- add a paragrapf in "The information needed in Quality Assurance documentation is:
"Agile methods reflect the actual working flow inside each phase of the development process. Agile methods complying to the V-Model should deliver the artifacts ensuring the quality and the proof of compliance to the CENELEC for each of the phases. The roles involved in the agile project should be identified in a clear way describing how the roles inside the project comply with the roles indentified in the CENELEC standard."
- replace "a table called the" by "the document" and reference it to the task deliverable.

p12:
- exchange "Final report" with "Final report on one iteration" adding "After the milestone the results are picked up in the agile process.".

p13, 14:
- the chapter will be written in the deliverable of the task. The information about the reference will be added by @FrederiqueVallee in the clarificatoin of the review.
- concerning safety requirements of "non-vital" implementation. 
  - within the FPP the development is intended to be performed according to the CENELEC norm
  - the context of use "non-vital" needs a description to answer to this question @KlausRuedigerHase where is "non-vital" defined in the scope of our project? (a definition inside the software quality assurance plan is expected)

p15:
- comment: "The agile approach is expected to be described inside the documents from the planning phase (this document is also part of the planning phase) and will be part of the development and the assessment. Agile methods are alway part of the development and thus will be assesed. The assessment itself is also performed in an  agile making use of the project ecosystem. The deliverables itself will be a snapshot at the milestone."
there is a pragraph missing describing the agility inside the internal assessment

p18:
- replace "Internal Assessment" with "Assessment" (throughout the document) and reference to class A body according to EN17020

- remove "... strongly..."

**Comment by MarcBehrens** [comment]
Review comment from @AbdelnasirMohamed:
The review version of the QA plan will be available for internal assessment by the 23rd of October 2015.

**Comment by FrederiqueVallee** [comment]
References to CENELEC 50128 are not needed in the Assessment Plan.. However for clarification:
- P 12 and p 32 - Test specification requirements are given in:
     + § 6.1.4.4 for the Generic Software 
     + § 8.4.5.2 for the Application dat or algorithms
     + Table B.6 2) for Integration
- P 13 first remark - Test methods are required in Tables A.5, A.6 and A.7
- P 13 second remark - V&V process is described in §§ 6.2 and 6.3 and methods are required in Tables A.5, A.6, A.7 and A.8
- P 14 - Safety process and methods are numerous in the CENELEC (see for example §§ 6.3 and 7.3 and Tables A.3, A.8 and A.19)

**Comment by MarcBehrens** [comment]
- [ ] Review comments from Norbert to be insterted into the Assessment Plan
